### ISSUE TITLE
Issue with Chromium Windows 10 / Surface (tablet mode) + mouse behaviour

### ISSUE THREAD

**Issue by googleoryx** [patrickhlauke/touch#24] opened 2020-05-31 02:51 UTC
Hi @patrickhlauke

I raised this issue on Chromium just now:
https://bugs.chromium.org/p/chromium/issues/detail?id=1088262

I wanted to get your thoughts, as I saw you have compiled something here recently: https://patrickhlauke.github.io/touch/pointer-hover-any-pointer-any-hover/results/

The result that I'm concerned with is the behaviour of `Windows 10 / Surface (tablet mode) + mouse / Chrome 81` compared to `Windows 10 / Surface (tablet mode) + mouse / Firefox 75.0`. I believe Firefox's behaviour is correct here.

If you could chime in on the bug report in Chromium that would be great.

**Comment by patrickhlauke** [comment] 2020-05-31 10:35
Yup, thanks for the heads-up. Commented on the bug there (initially thought it was a dupe of https://bugs.chromium.org/p/chromium/issues/detail?id=1028118 but nah, different but still wrong

**Closed as completed by patrickhlauke** 2020-05-31 10:35 UTC
